### ISSUE TITLE
Add docs to explain how to use `sbt-release-early` in Travis

### ISSUE THREAD

**Issue by jvican** [scalacenter/sbt-release-early#2]
The plugin has been built with this functionality in mind and is CI independent.
  
This only requires adding docs to the README and maybe add a few lines of code to make Travis support more intuitive / out-of-the-box.

**Comment by jvican** [comment]
I cannot get this done any time soon, but as explained in the wiki section, I welcome a contribution to add Travis configuration. You can inspire yourself from [Drone's wiki section](https://github.com/scalacenter/sbt-release-early/wiki/How-to-release-in-Drone-(CI)), which goes a lot into detail.

**Comment by kwark** [comment]
@jvican I updated the wiki and updated the Travis CI section.

**Comment by jvican** [comment]
That's an excellent contribution. I cannot add anything else. Thank you very much @kwark.
