### ISSUE TITLE
Skip re-releases

### ISSUE THREAD

**Issue by JanBessai** [scalacenter/sbt-release-early#25]
It would be great, if sbt-release would detect if it is run on a previously released version. This happens in CI, when a build is re-started after one successful release has been made.

**Comment by jvican** [comment]
Indeed, I agree this is desirable. I will implement it because i need it in bloop.

**Comment by JanBessai** [comment]
Thanks!!

Not sure, if anybody would want this, but in your last commit,  maybe there should be a config option to enable the old behavior and fail.

**Comment by jvican** [comment]
I actually think this should be the default, if someone wants to publish twice because that has a "side effect" to make things work, then they're probably doing it wrong :smile:.

**Comment by jvican** [comment]
I'm cutting a 1.0.0 release after I've merged #27, which allows users to ignore the local repository by default. If you want not to ignore the local repo, modify the pertinent key :smile:.
