### ISSUE TITLE
sbt-release-early not found

### ISSUE THREAD

**Issue by adamw** [scalacenter/sbt-release-early#6]
I added `addSbtPlugin("ch.epfl.scala" % "sbt-release-early" % "1.0.4")` to `project/plugins.sbt`, however sbt (0.13.15) doesn't find the artifact.

It's looking for:

`https://repo1.maven.org/maven2/ch/epfl/scala/sbt-release-early_2.10_0.13/1.0.4/sbt-release-early-1.0.4.pom`

while there only exists:

`https://repo1.maven.org/maven2/ch/epfl/scala/sbt-release-early/1.0.4/sbt-release-early-1.0.4.pom`

This seems a rather basic thing to use the plugin, am I missing some sbt setting?

**Comment by jvican** [comment]
This was caused by sbt-bintray, who does not publish maven style plugins correctly to Bintray nor Central. I've just added sbt-sonatype support, so the plugin will use it as it's underlying publisher. This means that I'll publish a stable release very soon. For now, you can depend on this version:
```scala
addSbtPlugin("ch.epfl.scala" % "sbt-release-early" % "1.0.4+8-2e879ede+20170721-1345")
```

**Comment by jvican** [comment]
Note that I still need to update docs, but I left you some instructions in Gitter: https://gitter.im/scalacenter/sbt-release-early?at=59720f4ac101bc4e3aa950e1. Hope that's useful! :smile:.
